# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shh < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.0/shh_Darwin_x86_64.tar.gz"
      sha256 "e09c5b3d148fa5b5c1f1b3ee02e9f3e5a89eb4a780916367180779b4eb393b67"

      def install
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.0/shh_Darwin_arm64.tar.gz"
      sha256 "78f98fdc9bb214fc78901c19187d617c24b2fbc038ab984eb06ed7f3c43a3f57"

      def install
        bin.install "shh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.0/shh_Linux_x86_64.tar.gz"
      sha256 "dda0fe0ff1a401fed2f07863ab0d0b725386abaebd51a70be4774b7548c66c19"

      def install
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.0/shh_Linux_arm64.tar.gz"
      sha256 "fe99dc287c4207ed65ae92db75a4187626344e638e06e9122a58534468999f6d"

      def install
        bin.install "shh"
      end
    end
  end
end
