# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shh < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.1/shh_Darwin_arm64.tar.gz"
      sha256 "28a710978077a7cbcf6836b77da5697bf08a1bc9baf3e13dc36b054f7fbfefdc"

      def install
        bin.install "shh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.1/shh_Darwin_x86_64.tar.gz"
      sha256 "006a337154cac6d98c1027cf55cd12afb3d88246a338e72fc3abdd0bda44b893"

      def install
        bin.install "shh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.1/shh_Linux_x86_64.tar.gz"
      sha256 "1d834c97c991f34d46e52bdc82cb60503a32338f91ac109b9434d82638e9885e"

      def install
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.1/shh_Linux_arm64.tar.gz"
      sha256 "3282a111f17bc65f9a58da0e875c4a3b1fc1500b53a1c57938524b7ec77ca06d"

      def install
        bin.install "shh"
      end
    end
  end
end
