# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shh < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.2/shh_Darwin_x86_64.tar.gz"
      sha256 "411dc65c976fc0cef13dd828577a633c86b8d63b43596b9ddad5121ac870a385"

      def install
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.2/shh_Darwin_arm64.tar.gz"
      sha256 "d8d712452b3928107bc03b5e8390400b5473df7a3b494bc4630b188884ce4e18"

      def install
        bin.install "shh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.2/shh_Linux_arm64.tar.gz"
      sha256 "11b71178b687fa76145765fb833f651ce05f8f13649a3d0a2514e81575fa11ac"

      def install
        bin.install "shh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robbiecloset/shh/releases/download/v0.1.2/shh_Linux_x86_64.tar.gz"
      sha256 "1dc380af4d33b816a1c2cc455f506b9c295dc16222569bb15e4592ab54de3b6b"

      def install
        bin.install "shh"
      end
    end
  end
end
